---
author: "G. Moroz"
output: 
  html_document:
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
library(tidyverse)
library(rvest)
```
```{r, include=FALSE, eval=FALSE}
# обкачаем страницу со списком сотрудников и их личными страницами
source <- read_lines("https://ling.hse.ru/persons") 

# возьмем оттуда все личные страницы
data_frame(links = source) %>% 
  filter(str_detect(links, '<a class="fa-person__name"')) %>%
  mutate(links = str_extract(links, "www.hse.ru/.*"),
         links = str_replace(links, '">', "")) %>% 
  distinct() ->
  staff

# создадим пустой датафрейм, который потом будет заполняться
publications <- data_frame(links = NA, full_names = NA, publications = NA)

# запустим цикл по всем старницам
sapply(1:nrow(staff), function(i){
# скачаем со страницы публикации сотрудников
  source <- read_html(paste0("https://", staff$links[i]))
  source %>% 
    html_nodes("div.large") %>%
    html_text() ->
    pubs
  source %>% 
# скачаем со страницы имена сотрудников
  html_nodes("h1") %>%
  html_text() ->
    name
  publications <<- rbind(publications, data_frame(links = staff$links[i], 
                                                  full_names = name[1],
                                                  publications = pubs))
  })

# преобразуем имена в отдельные столбцы
publications %>% 
  slice(-1) %>% 
  rowwise() %>% 
  mutate(names = str_split(full_names, " ", simplify = TRUE)[2],
         patronymic = str_split(full_names, " ", simplify = TRUE)[3],
         surname = str_split(full_names, " ", simplify = TRUE)[1],
         type = str_extract(publications, "Книга|Статья|Глава книги|Препринт"),
         publications = str_replace(publications, "Книга |Статья |Глава книги |Препринт ", ""),
         year = str_extract(publications, "20\\d{2}|199\\d{1}")) %>% 
  select(links, names, patronymic, surname, type, year, publications) %>% 
  write_csv("lingschool_pubs.csv")
```

```{r, include=FALSE}
df <- read_csv("lingschool_pubs.csv")
```
```{r}
df %>% 
  mutate(surname = paste0('<a href="http://', links, '" target="_blank">', surname, '</a>')) %>% 
  select(-links) %>% 
  DT::datatable(filter = 'top', rownames = FALSE, options = list(pageLength = 50, dom = 'tip'), escape = FALSE)
```

